fields:
  color:
    description: Color of the object
    field_type: String
  weight:
    description: Weight of the object
    field_type:
      Float:
        unit: kg
  energy_density:
    description: Calories of food
    field_type:
      Float:
        unit: KJ/kg
  fat_density:
    description: Fat in food
    field_type:
      Float:
        unit: kg/kg
data_sources:
  - Mock:
      data_path: food_1.yaml
  - Rest:
      base_url: http://localhost:5000
